### ISSUE TITLE
Deductible

### ISSUE THREAD

**Issue by peaceypz** [lemonade-hq/policy-2.0#9]
Deductible - can it be a percentage of the item claim rather than a nominal amount?  This is policy holder knows exactly what the deductible is no matter if one item or multiple items are damaged.

**Comment by ckvo** [comment]
@peaceypz Thanks for the suggestion. We've chosen set the deductible as a fixed nominal amount as this should provide users with more certainty. Just to clarify, the deductible applies for each event not for each item - so if you have multiple items damaged due to one event, you only pay one fixed dollar deductible!

**Comment by peaceypz** [comment]
500 could be a lot for a young professional therefore a set % on the item might be more relatable. 

-------- Original Message --------

**Comment by ckvo** [comment]
@peaceypz Oh the $500 is just for illustration. Users can always select a lower deductible - even to as low as zero with Lemonade.

> Opting for a higher deductible means you’re taking more of the risk on yourself, so it is often a way to lower your monthly payments. You can increase or decrease your deductible... It’s up to you.

**Comment by peaceypz** [comment]
Got it thank you 

-------- Original Message --------
